/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './angular-module-starter.module';
import * as import2 from './angular-module-starter.service';
class AngularModuleStarterModuleInjector extends import0.ɵNgModuleInjector<import1.AngularModuleStarterModule> {
  _AngularModuleStarterModule_0:import1.AngularModuleStarterModule;
  __AngularModuleStarterService_1:any;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _AngularModuleStarterService_1():any {
    if ((this.__AngularModuleStarterService_1 == null)) { (this.__AngularModuleStarterService_1 = import1.asyncLocalStorageFactory()); }
    return this.__AngularModuleStarterService_1;
  }
  createInternal():import1.AngularModuleStarterModule {
    this._AngularModuleStarterModule_0 = new import1.AngularModuleStarterModule();
    return this._AngularModuleStarterModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.AngularModuleStarterModule)) { return this._AngularModuleStarterModule_0; }
    if ((token === import2.AngularModuleStarterService)) { return this._AngularModuleStarterService_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AngularModuleStarterModuleNgFactory:import0.NgModuleFactory<import1.AngularModuleStarterModule> = new import0.NgModuleFactory<any>(AngularModuleStarterModuleInjector,import1.AngularModuleStarterModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21hY2Jvb2twcm8vUHJvamVjdHMvNkNvbXBUZXN0L3NyYy9hbmd1bGFyLW1vZHVsZS1zdGFydGVyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9tYWNib29rcHJvL1Byb2plY3RzLzZDb21wVGVzdC9zcmMvYW5ndWxhci1tb2R1bGUtc3RhcnRlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
