/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './angular-module-starter.component';
import * as import2 from './angular-module-starter.service';
const styles_AngularModuleStarterComponent:any[] = ([] as any[]);
export const RenderType_AngularModuleStarterComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AngularModuleStarterComponent,
  data: {}
}
);
export function View_AngularModuleStarterComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Fuck you Bitch'])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.AngularModuleStarterComponent = v.component;
    const currVal_0:any = co.message;
    ck(v,2,0,currVal_0);
  });
}
function View_AngularModuleStarterComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'angular-module-starter',([] as any[]),(null as any),(null as any),(null as any),View_AngularModuleStarterComponent_0,RenderType_AngularModuleStarterComponent)),
    import0.ɵdid(24576,(null as any),0,import1.AngularModuleStarterComponent,[import2.AngularModuleStarterService],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AngularModuleStarterComponentNgFactory:import0.ComponentFactory<import1.AngularModuleStarterComponent> = import0.ɵccf('angular-module-starter',import1.AngularModuleStarterComponent,View_AngularModuleStarterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21hY2Jvb2twcm8vUHJvamVjdHMvNkNvbXBUZXN0L3NyYy9hbmd1bGFyLW1vZHVsZS1zdGFydGVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9tYWNib29rcHJvL1Byb2plY3RzLzZDb21wVGVzdC9zcmMvYW5ndWxhci1tb2R1bGUtc3RhcnRlci5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9tYWNib29rcHJvL1Byb2plY3RzLzZDb21wVGVzdC9zcmMvYW5ndWxhci1tb2R1bGUtc3RhcnRlci5jb21wb25lbnQudHMuQW5ndWxhck1vZHVsZVN0YXJ0ZXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL21hY2Jvb2twcm8vUHJvamVjdHMvNkNvbXBUZXN0L3NyYy9hbmd1bGFyLW1vZHVsZS1zdGFydGVyLmNvbXBvbmVudC50cy5Bbmd1bGFyTW9kdWxlU3RhcnRlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8aDE+e3ttZXNzYWdlfX08L2gxPlxuICAgICAgICA8cD5GdWNrIHlvdSBCaXRjaDwvcD5cbiAgICAiLCI8YW5ndWxhci1tb2R1bGUtc3RhcnRlcj48L2FuZ3VsYXItbW9kdWxlLXN0YXJ0ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUNRO0lBQUk7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUFnQjtJQUNwQjtJQUFHO0lBQWtCOzs7O0lBRGpCO0lBQUE7Ozs7O0lDRFo7Z0JBQUE7Ozs7In0=
