/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './jason-test.component';
const styles_JasonRocksComponent:any[] = ([] as any[]);
export const RenderType_JasonRocksComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_JasonRocksComponent,
  data: {}
}
);
export function View_JasonRocksComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Another component to show you have multiple elements now in a single package.'])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.JasonRocksComponent = v.component;
    const currVal_0:any = co.message;
    ck(v,2,0,currVal_0);
  });
}
function View_JasonRocksComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'jason-rocks',([] as any[]),(null as any),(null as any),(null as any),View_JasonRocksComponent_0,RenderType_JasonRocksComponent)),
    import0.ɵdid(24576,(null as any),0,import1.JasonRocksComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const JasonRocksComponentNgFactory:import0.ComponentFactory<import1.JasonRocksComponent> = import0.ɵccf('jason-rocks',import1.JasonRocksComponent,View_JasonRocksComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21hY2Jvb2twcm8vUHJvamVjdHMvNkNvbXBUZXN0L3NyYy9qYXNvbi10ZXN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9tYWNib29rcHJvL1Byb2plY3RzLzZDb21wVGVzdC9zcmMvamFzb24tdGVzdC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9tYWNib29rcHJvL1Byb2plY3RzLzZDb21wVGVzdC9zcmMvamFzb24tdGVzdC5jb21wb25lbnQudHMuSmFzb25Sb2Nrc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvbWFjYm9va3Byby9Qcm9qZWN0cy82Q29tcFRlc3Qvc3JjL2phc29uLXRlc3QuY29tcG9uZW50LnRzLkphc29uUm9ja3NDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgPGgxPnt7bWVzc2FnZX19PC9oMT5cbiAgICAgICAgPHA+QW5vdGhlciBjb21wb25lbnQgdG8gc2hvdyB5b3UgaGF2ZSBtdWx0aXBsZSBlbGVtZW50cyBub3cgaW4gYSBzaW5nbGUgcGFja2FnZS48L3A+XG4gICAgIiwiPGphc29uLXJvY2tzPjwvamFzb24tcm9ja3M+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ1E7SUFBSTtNQUFBO01BQUE7SUFBQTtJQUFBO0lBQWdCO0lBQ3BCO0lBQUc7SUFBaUY7Ozs7SUFEaEY7SUFBQTs7Ozs7SUNEWjtnQkFBQTs7OzsifQ==
